object Versions {
    const val androidCore = "1.7.0"
    const val appCompat = "1.4.1"
    const val material = "1.5.0"
    const val constraintLayout = "2.1.3"
    const val koin = "3.1.5"
    const val mockk = "1.12.0"
    const val flowTurbine = "0.7.0"
    const val mockWebServer = "4.9.3"
    const val junit = "4.13.2"
    const val androidJunit = "1.1.3"
    const val espresso = "3.4.0"
    const val retrofit = "2.7.0"
    const val httpLoggingInterceptor = "4.9.3"
    const val coroutines = "1.5.1"
    const val pagingJetpack = "3.1.0"
    const val glide = "4.13.0"
    const val testCoroutines = "1.6.0"
    const val lifecycleExtensions = "2.2.0"
    const val lifecycleViewModel = "2.4.0"
    const val androidArchTesting = "2.1.0"
    const val androidxTest = "1.4.0"
    const val androidxTestExtJunit = "1.1.3"
}